---
title: "Expression & Sensitivity Analysis with Erlotinib and Afatanib"
output: html_notebook
---



```{r, echo=FALSE, echo=FALSE}
library(data.table)
library(ggplot2)
library(PharmacoGx)
```

```{r, Functions}


processSummSensPset <- function(df) {
  df2 = as.data.frame(t(data.frame(df)))
  df2$cell_line = gsub("—|-| |_|\\.","", rownames(df2))
  print(paste0("duplicated rows ", df2[duplicated(df2$cell_line),]))
  df2[-duplicated(df2$cell_line),]
  return(df2)
}


medianWithoutNA<-function(x) {
   median(x[which(!is.na(x))])
}
```

smmart expression for DUOX1 
ENST00000389037
RNA170210CC_DNA-17-00536_S1= 0.447007 -> log2(0.438339)= -1.189881
RNA170210CC_L1-C1-0000254583_S2=2.75051 --> log2(2.65087) = 1.406466


ENST00000321429
RNA170210CC_DNA-17-00536_S1= log(0.060739) = -2.801
RNA170210CC_L1-C1-0000254583_S2 = 0.269417 = -1.311

EGFR
RNA170210CC_DNA-17-00536_S1 = log(2.19) = 0.784
RNA170210CC_L1-C1-0000254583_S2 = log(4.445) = 1.492
#DUOX1 EXPRESSION
-----------------
```{r, DUOX UHN expression}

uhn_samplelist=fread("/Volumes/exacloud/CompBio/UHN/SRR_cellline_GSM.tsv", header=F)
kallisto_uhn=fread("/Volumes/exacloud/CompBio/UHN/DUOX_kallisto.txt", col.names = c("target_id","length","eff_length","est_counts","tpm","SRA_ID"))
kuid=sapply(strsplit(kallisto_uhn$target_id, split="[|]"), "[", 1)
exp_uhn= cbind(merge(kallisto_uhn, uhn_samplelist[,c(1,2)], by.x="SRA_ID", by.y="V1")[,c("V2", "tpm")], transcriptid=kuid)
uhn21exp = exp_uhn[transcriptid=="ENST00000321429.8", c("V2", "tpm")]
uhn89exp = exp_uhn[transcriptid=="ENST00000389037.7",c("V2", "tpm")]
colnames(uhn89exp) = c("cellline", "tpm_value")

```


```{r DUOX BRCA gray/heiser bccl expression data }

gray_samplist = fread("/Volumes/exacloud/CompBio/BCCL/SraRunTable.txt")
kallisto_gray =fread("/Volumes/exacloud/CompBio/BCCL/output_kallisto/DUOX_kallisto.txt", col.names = c("target_id","length","eff_length","est_counts","tpm","SRA_ID"))
kgid=sapply(strsplit(kallisto_gray$target_id, split="[|]"), "[", 1)
#combines cell names to SRR names, and split column with transcript name rbind
exp_gray= cbind(merge(kallisto_gray, gray_samplist[,c(8,11)], by.x="SRA_ID", by.y="Run_s")[,c("tpm", "cell_line_s")], transcriptid=kgid)
gray21 = exp_gray[transcriptid=="ENST00000321429.8", c("cell_line_s", "tpm")]
gray89 = exp_gray[transcriptid=="ENST00000389037.7",c("cell_line_s", "tpm")]

#duplicated samples both expression equals zero
gray21exp=gray21[-(which(gray21$cell_line_s=="UACC812")[1]),]
gray89exp=gray89[-(which(gray89$cell_line_s=="UACC812")[1]),]
colnames(gray89exp) = c("cellline", "tpm_value")

```

```{r DUOX CCLE expression}
ccle21 = fread("/Users/patterja/Workspace/ccle_tcga_kallisto/CCLE_ENST00000321429.csv")
ccle89 = fread("/Users/patterja/Workspace/ccle_tcga_kallisto/CCLE_ENST00000389037.csv")
tcga21 = fread("/Users/patterja/Workspace/ccle_tcga_kallisto/TCGA_ENST0000032149.csv")
tcga89 = fread("/Users/patterja/Workspace/ccle_tcga_kallisto/TCGA_ENST00000389037.csv")

ccle21_brca = ccle21[cancer_type=="BRCA",c("ccle_name","tpm_value")]
ccle89_brca = ccle89[cancer_type=="BRCA",c("ccle_name","tpm_value")]
tcga21_brca = tcga21[cancer_type=="BRCA",c("AliquotBarcode","tpm_value")]
tcga89_brca = tcga89[cancer_type=="BRCA",c("AliquotBarcode","tpm_value")]

ccle21_brca$ccle_name = sapply(strsplit(ccle21_brca$ccle_name, split="[.]"), "[",2)
ccle89_brca$ccle_name = sapply(strsplit(ccle89_brca$ccle_name, split="[.]"), "[",2)

ccle21_brca$cellline = gsub("—|-| |_","", ccle21_brca$ccle_name)
ccle89_brca$cellline = gsub("—|-| |_","", ccle89_brca$ccle_name)
ccle21exp=ccle21_brca[,c("cellline", "tpm_value")]
ccle89exp=ccle89_brca[,c("cellline", "tpm_value")]

```



```{r DUOX combine}

exp89=Reduce(function(x, y) merge(x, y, by="cellline", all=TRUE), list(gray89exp, uhn89exp, ccle89exp))
colnames(exp89)= c("cellline", "GRAY", "UHN", "CCLE")



exp89$median_duox = apply(exp89[,c(2:4)], 1, medianWithoutNA)

```

#EGFR EXPRESSION
----------------

ENST00000344576.6
ENST00000342916.7
ENST00000420316.6
ENST00000454757.6
ENST00000638463.1
ENST00000455089.5
ENST00000450046.1

omitt none coding transcripts
ENST00000463948
ENST00000459688
ENST00000485503


```{r EGFR GRAY BRCA gray/heiser bccl expression }

gray_samplist = fread("/Volumes/exacloud/CompBio/BCCL/SraRunTable.txt")
kallisto_gray_egfr =fread("/Volumes/exacloud/CompBio/BCCL/output_kallisto/EGFR_kallisto.txt", col.names = c("target_id","length","eff_length","est_counts","tpm","SRA_ID"))

kgid=sapply(strsplit(kallisto_gray_egfr$target_id, split="[|]"), "[", 1)
#combines cell names to SRR names, and split column with transcript name rbind
exp_gray= cbind(merge(kallisto_gray_egfr, gray_samplist[,c(8,11)], by.x="SRA_ID", by.y="Run_s")[,c("tpm", "cell_line_s")], transcriptid=kgid)[,c(2,1)]
grayEgfr_exp = exp_gray[, lapply(.SD, sum, na.rm=TRUE), by = cell_line_s]

colnames(grayEgfr_exp) = c("cellline", "tpm_value")

```



```{r EGFR UHN expression}

uhn_samplelist=fread("/Volumes/exacloud/CompBio/UHN/SRR_cellline_GSM.tsv", header=F)
kallisto_uhn=fread("/Volumes/exacloud/CompBio/UHN/EGFR_kallisto.txt", col.names = c("target_id","length","eff_length","est_counts","tpm","SRA_ID"))
kuid=sapply(strsplit(kallisto_uhn$target_id, split="[|]"), "[", 1)
exp_uhn= cbind(merge(kallisto_uhn, uhn_samplelist[,c(1,2)], by.x="SRA_ID", by.y="V1")[,c("V2", "tpm")], transcriptid=kuid)[,c(2,1)]
uhnEgfr_exp = exp_uhn[, lapply(.SD, sum, na.rm=TRUE), by = V2]

colnames(uhnEgfr_exp) = c("cellline", "tpm_value")

```


```{r EGFR CCLE}


ccle_egfr=fread("/Users/patterja/Workspace/ccle_tcga_kallisto/EGFR_CCLE.csv")
#Filter for BRCA and coding EGFR

#clean up ccle_name
ccle_egfr$ccle_name=sapply(strsplit(ccle_egfr$ccle_name, split="[.]"), "[",2)
ccle_egfr$cellline=gsub("—|-| |_","", ccle_egfr$ccle_name)

#Filter for BRCA
#Filter coding EGFR
#select columns to sum
#sum by cell line name
ccleEgfr_exp = ccle_egfr[cancer_type =="BRCA",][!grepl("ENST00000463948|ENST00000459688|ENST00000485503",transcript_id),][,c("cellline","tpm_value")][, lapply(.SD, sum, na.rm=TRUE), by = cellline]




```


```{r EGFR combine}

expEgfr=Reduce(function(x, y) merge(x, y, by="cellline", all=TRUE), list(grayEgfr_exp, uhnEgfr_exp, ccleEgfr_exp))
colnames(expEgfr)= c("cellline", "GRAY", "UHN", "CCLE")


expEgfr$median_egfr = apply(expEgfr[,c(2:4)], 1, medianWithoutNA)

```


#RAF Expression
```{r raf1 BRCA gray/heiser bccl expression data, eval=FALSE }

gray_samplist = fread("/Volumes/exacloud/CompBio/BCCL/SraRunTable.txt")
kallisto_gray =fread("/Volumes/exacloud/CompBio/BCCL/output/RAF1_kallisto.txt", col.names = c("target_id","length","eff_length","est_counts","tpm","SRA_ID"))

kgid=sapply(strsplit(kallisto_gray$target_id, split="[|]"), "[", 1)
#combines cell names to SRR names, and split column with transcript name rbind
exp_gray= cbind(merge(kallisto_gray, gray_samplist[,c(8,11)], by.x="SRA_ID", by.y="Run_s")[,c("tpm", "cell_line_s")], transcriptid=kgid)[,c(1,2)]

expgrayRAF = exp_gray[, lapply(.SD, sum, na.rm=TRUE), by = cell_line_s]

grayEgfr_exp = exp_gray[, lapply(.SD, sum, na.rm=TRUE), by = cell_line_s]

colnames(grayEgfr_exp) = c("cellline", "tpm_value")

```

#DRUG Sensitivity

```{r read in pharmaco data, echo=FALSE}
availablePSets()
pharm_ccle2013=downloadPSet("CCLE_2013")
pharm_ccle = downloadPSet("CCLE")
pharm_gdsc = downloadPSet("GDSC")
pharm_gdsc2013 = downloadPSet("GDSC_2013")
pharm_gdsc1000 = downloadPSet("GDSC1000")
pharm_gcsi=downloadPSet("gCSI")
pharm_fimm=downloadPSet("FIMM")
pharm_ctrpv2=downloadPSet("CTRPv2")


pharm_ccle2013_reauc = summarizeSensitivityProfiles(pSet = pharm_ccle2013, sensitivity.measure = 'auc_published', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
pharm_ccle_reauc = summarizeSensitivityProfiles(pSet = pharm_ccle, sensitivity.measure = 'auc_recomputed', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
pharm_gdsc_reauc = summarizeSensitivityProfiles(pSet = pharm_gdsc, sensitivity.measure = 'auc_recomputed', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
pharm_gdsc2013_reauc = summarizeSensitivityProfiles(pSet = pharm_gdsc2013, sensitivity.measure = 'auc_published', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
pharm_gdsc1000_reauc = summarizeSensitivityProfiles(pSet = pharm_gdsc1000, sensitivity.measure = 'auc_recomputed', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
pharm_gcsi_reauc = summarizeSensitivityProfiles(pSet = pharm_gcsi, sensitivity.measure = 'auc_recomputed', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
pharm_fim_reauc = summarizeSensitivityProfiles(pSet = pharm_fimm, sensitivity.measure = 'auc_recomputed', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))
#ctrp will take a lifetime to summarize. beware.
pharm_ctrp_reauc = summarizeSensitivityProfiles(pSet = pharm_ctrpv2, sensitivity.measure = 'auc_recomputed', summary.stat = "median", verbose=T, drugs=c("Erlotinib", "Afatinib"))

ccle_auc = processSummSensPset(pharm_ccle_reauc)
gdsc_auc = processSummSensPset(pharm_gdsc_reauc)
gdsc1000_auc = processSummSensPset(pharm_gdsc1000_reauc)
gcsi_auc = processSummSensPset(pharm_gcsi_reauc)
fimm_auc = processSummSensPset(pharm_fim_reauc)
ctrpv2_auc = processSummSensPset(pharm_ctrp_reauc)


auc_erlo = Reduce(function(x, y) merge(x, y, by="cell_line", all=TRUE), list(ccle_auc[,c(1,3)], gdsc_auc[,c(1,3)], gdsc1000_auc[,c(1,3)], gcsi_auc[,c(1,3)], fimm_auc[,c(1,3)], ctrpv2_auc[,c(1,3)]))
colnames(auc_erlo) = c("cell_line", "CCLE", "GDSC","GDSC1000", "GCSI", "FIMM", "CTRPV2")

auc_afat = Reduce(function(x, y) merge(x, y, by="cell_line", all=TRUE), list(ccle_auc[,c(2,3)], gdsc_auc[,c(2,3)], gdsc1000_auc[,c(2,3)], gcsi_auc[,c(2,3)], fimm_auc[,c(2,3)], ctrpv2_auc[,c(2,3)]))
colnames(auc_afat) = c("cell_line", "CCLE", "GDSC","GDSC1000", "GCSI", "FIMM", "CTRPV2")



```




```{r fullset}
save(auc_erlo, file="/Users/patterja/Workspace/DrugPrioritization/SMMARTdrugViz/data/auc_erlo.Rda")
save(exp89, file="/Users/patterja/Workspace/DrugPrioritization/SMMARTdrugViz/data/exp89.Rda")
save(expEgfr, file="/Users/patterja/Workspace/DrugPrioritization/SMMARTdrugViz/data/expEgfr.Rda")

auc_erlo_noGDSC = auc_erlo[,-which(colnames(auc_erlo)=="GDSC")]
auc_erlo_noGDSCnoNA = auc_erlo_noGDSC[!rowSums(is.na(auc_erlo_noGDSC))>4,]

duoxexp_filt = exp89[exp89$cellline %in% auc_erlo_noGDSCnoNA$cell_line,]
duox_order = duoxexp_filt$cellline[c(order(duoxexp_filt$median_duox))]


aucErlo_filt = auc_erlo[auc_erlo$cell_line %in% duox_order,]
egfrexp_filt = expEgfr[expEgfr$cellline %in% duox_order,]

duoxexp_filt$cellline = factor(duoxexp_filt$cellline, levels=duox_order)
egfrexp_filt$cellline = factor(egfrexp_filt$cellline, levels=duox_order)

mel=melt(duoxexp_filt[,c(1:4)], id.vars="cellline", measure=c("GRAY","UHN","CCLE"))
mel$value[which(mel$value<1e-10)]=1e-10

mee=melt(egfrexp_filt[,c(1:4)], id.vars="cellline", measure=c("GRAY","UHN","CCLE"))
mee$value[which(mee$value<1e-10)]=1e-10




```


```{r, figures}

duox_erlo_heatmap <- ggplot(mel,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "DUOX1", x=element_blank()) +
  theme(panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(color="black"),
        plot.margin=unit(c(0,0,-20,1), "mm")) +
  scale_fill_gradientn(name=expression(paste("log"[2],"TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(9.313226e-10,9.536743e-07,0.0009765625,1),
                       labels=c("-30","-20","-10","1")) +
  coord_fixed(ratio = 1)


egfr_erlo_heatmap <- ggplot(mee,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "EGFR", x="cell line") +
  theme(panel.background = element_blank(),
        plot.margin=unit(c(-20,0,0,1), "mm"), 
        axis.text.y = element_text(color="black"),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_gradientn(name=expression(paste("log"[2],"TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(9.313226e-10,9.536743e-07,0.0009765625,1),
                       labels=c("-30","-20","-10","1")) +
  coord_fixed(ratio = 1)
  
p=grid.arrange(duox_erlo_heatmap, egfr_erlo_heatmap, ncol=1, nrow=2)

#scale_fill_gradientn(name=expression(paste("TPM")), 
#                       colours=c("navyblue","darkmagenta","darkorange1"), 
#                       na.value="transparent", 
#                       trans = 'log2',
#                       breaks=c(1e-8,1e-6,1e-4,1e-2,1),
#                       labels("1e-8","1e-6","1e-4","1e-2","0")) +
    
```

```{r GEOM_POINT Erlotinib}
#Filter for duox order
aucErlo_filt = auc_erlo_noGDSCnoNA[auc_erlo_noGDSCnoNA$cell_line %in% duox_order,]
auc_erlo_noGDSCnoNA = auc_erlo_noGDSC[!rowSums(is.na(auc_erlo_noGDSC))>4,]


aucErlo_filt$cell_line = factor(aucErlo_filt$cell_line, levels=duox_order)
mec_auc=melt(aucErlo_filt, id.vars="cell_line", measure=c("CCLE","GDSC1000","GCSI","FIMM","CTRPV2"))

#only GDSC1000
aucErlo_filtGDSC1000 = aucErlo_filt[,c("cell_line","GDSC1000")]
mec_auc=melt(aucErlo_filt, id.vars="cell_line", measure=c("GDSC1000"))


erlo_scatter <- ggplot(mec_auc, aes(x=cell_line, y=value)) +
  geom_point(aes(colour=factor(variable))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.background = element_rect(fill="white", colour = "black"),
        axis.text=element_text(colour="black"),
        legend.title = element_blank(),
        panel.grid.major.x = element_line( size=.1, color="gray" ) ) +
  scale_colour_brewer(palette = "Dark2") +
  labs(y="AAC", x="cell lines\nordered by increasing DUOX1 expression") +
  ylim(0, 0.3)
  

```

# AFATANIB ------------------------------------------------------------------------------



```{r fullset afat}

auc_afat_noGDSC = auc_afat[,c("cell_line", "GDSC1000")]
auc_afat_noGDSCnoNA = na.omit(auc_afat_noGDSC)

duoxexp_filt = exp89[exp89$cellline %in% auc_afat_noGDSCnoNA$cell_line,]
duox_order = duoxexp_filt$cellline[c(order(duoxexp_filt$median_duox))]

aucAfat_filt = auc_afat[auc_afat$cell_line %in% duox_order,]

egfrexp_filt = expEgfr[expEgfr$cellline %in% duox_order,]


duoxexp_filt$cellline = factor(duoxexp_filt$cellline, levels=duox_order)
egfrexp_filt$cellline = factor(egfrexp_filt$cellline, levels=duox_order)

mel=melt(duoxexp_filt[,c(1:4)], id.vars="cellline", measure=c("GRAY","UHN","CCLE"))
mel$value[which(mel$value<1e-6)]=1e-7

mee=melt(egfrexp_filt[,c(1:4)], id.vars="cellline", measure=c("GRAY","UHN","CCLE"))
mee$value[which(mee$value<1e-6)]=1e-7


duox_afat_heatmap <- ggplot(mel,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "DUOX1", x=element_blank()) +
  theme(panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(color="black"),
        plot.margin=unit(c(0,0,-20,1), "mm")) +
  scale_fill_gradientn(name=expression(paste("log"[2],"TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(9.536743e-07,0.0009765625,1),
                       labels=c("-20","-10","1")) +
  coord_fixed(ratio = 1)


egfr_afat_heatmap <- ggplot(mee,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "EGFR", x="cell line") +
  theme(panel.background = element_blank(),
        plot.margin=unit(c(-20,0,0,1), "mm"), 
        axis.text.y = element_text(color="black"),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_gradientn(name=expression(paste("log"[2],"TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(9.536743e-07,0.0009765625,1),
                       labels=c("-20","-10","1")) +
  coord_fixed(ratio = 1)
  
p=grid.arrange(duox_afat_heatmap, egfr_afat_heatmap, ncol=1, nrow=2)


scale_fill_gradientn(name=expression(paste("TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(1e-8,1e-6,1e-4,1e-2,1),
                       labels("1e-8","1e-6","1e-4","1e-2","0")) +
```



```{r GEOM_POINT Afatanib}
#Filter1 only GDSC1000 has Afatinib data, remove na

aucAfat_filt$cell_line= factor(aucAfat_filt$cell_line, levels=duox_order)



#melt
mec_auc=melt(aucAfat_filt, id.vars="cell_line", measure=c("GDSC1000"))


afat_scatter <- ggplot(mec_auc, aes(x=cell_line, y=value)) +
  geom_point(aes(shape=factor(variable))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        panel.background = element_rect(fill="white", colour = "black"),
        axis.text=element_text(colour="black"),
        legend.title = element_blank(),
        panel.grid.major.x = element_line( size=.1, color="gray" ) ) +
  labs(y="AAC", x="cell line", shape=element_blank())



```



#--------Extra
```{r Sortings}

aucErlo_filt = auc_erlo[auc_erlo$cell_line %in% egfr_hdsort,]

# DUOX 
duoxexp_filt= exp89[exp89$cellline %in% aucErlo_filt$cell_line,]

# Duox expressing higher than 2.090010e-06 < 1.343570e-02 is junction
high_duox = duoxexp_filt[duoxexp_filt$median_duox > 2.090010e-06,]
low_duox = duoxexp_filt[duoxexp_filt$median_duox < 2.090010e-06,]


high_duoxsort =high_duox$cellline[c(order(high_duox$median_duox))]
low_duoxsort = low_duox$cellline[c(order(low_duox$median_duox))]

#reoder and sort
high_duox$cellline = factor(high_duox$cellline, levels=high_duoxsort)
low_duox$cellline = factor(low_duox$cellline, levels=low_duoxsort)


#EGFR

egfrexp_highduox = expEgfr[expEgfr$cellline %in% high_duoxsort,]
egfrexp_lowduox = expEgfr[expEgfr$cellline %in% low_duoxsort,]

#MERGING

exp = merge(x=high_duox, y=egfrexp_highduox, by="cellline", suffixes=c("duox", "egfr"), all=T)
exp = merge(x=low_duox, y=egfrexp_lowduox, by="cellline", suffixes=c("duox", "egfr"), all=T)

exp$cellline = factor(exp$cellline, levels=exp$cellline[c(order(exp$median_egfr))])
egfr_hdsort=exp$cellline[c(order(exp$median_egfr))]

```



```{r GEOM_TILE DUOX1+EGFR-Erlotinib HIGH}

# 3) and melt
preme=exp[,c(1:4)]
preme_egfr = exp[,c(1,6:8)]
colnames(preme) = c("cellline", "GRAY", "UHN", "CCLE")
colnames(preme_egfr) = c("cellline", "GRAY", "UHN", "CCLE")

med=melt(preme, id.vars="cellline", measure=c("GRAY","UHN","CCLE"))
mee=melt(preme_egfr, id.vars="cellline", measure=c("GRAY","UHN","CCLE"))

# 4) replace zero # remove -Inf because they don't behave well on geom_tile
med$value[which(med$value<6e-9)]=7e-9
mee$value[which(mee$value<5e-9)]=7e-9

#ENST00000389037
duox_erlo_heatmap <- ggplot(med,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "DUOX1", x=element_blank()) +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(color="black"),
        plot.margin=unit(c(0,0,-20,1), "mm")) +
  scale_fill_gradientn(name=expression(paste("TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(1e-8,1e-6,1e-4,1e-2,1),
                       labels("1e-8","1e-6","1e-4","1e-2","0")) +
  coord_fixed(ratio = 1)
                       

egfr_erlo_heatmap <- ggplot(mee,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "EGFR", x="cell line") +
  theme(panel.background = element_blank(),
        plot.margin=unit(c(-20,0,0,1), "mm"), 
        axis.text.y = element_text(color="black"),
        axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_fill_gradientn(name=expression(paste("TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(1e-8,1e-6,1e-4,1e-2,1),
                       labels("1e-8","1e-6","1e-4","1e-2","0")) +
  coord_fixed(ratio = 1)
  
p=grid.arrange(duox_erlo_heatmap, egfr_erlo_heatmap, ncol=1, nrow=2)
    
      
      scale_fill_gradientn(name=expression(paste("log"[2],"TPM")), 
                       colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       trans = 'log2',
                       breaks=c(9.536743e-07,0.0009765625,1),
                       labels=c("-20","-10","1")) +
  

```


    
    
```{r redundnat and not usesd DUOX1-AFATANIB}


# 1) Filter 
exp_filt= exp89[exp89$cellline %in% aucAfat_filt$cell_line,]
# 2) column names
colnames(exp_filt) = c("cellline", "GRAY", "UHN", "CCLE")
# 3) Median
exp_filt$median = apply(exp_filt[,c(2:4)], 1, medianWithoutNA)
# 4) and melt
mec_exp=melt(exp_filt, id.vars="cellline", measure=c("GRAY","UHN","CCLE"))
mec_exp$value[which(mec_exp$value<5.7e-9)]=6e-9


# 5) sort
mec_exp$cellline = factor(mec_exp$cellline, levels=exp_filt$cellline[c(order(exp_filt$median))])
duox1mediansortedCells = exp_filt$cellline[c(order(exp_filt$median))]

#write.table(exp_filt, file="/Users/patterja/Workspace/ccle_tcga_kallisto/duox_scaledexpression_forheatmap.txt", sep='\t', row.names=FALSE)
duox_afat_heatmap <- ggplot(mec_exp,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "DUOX1", x=element_blank()) +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(color="black"),
        plot.margin=unit(c(1,1,-17,1), "mm")) +
  scale_fill_gradientn(colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       name=expression(paste("TPM")),
                       trans = 'log2') +
  coord_fixed(ratio = 1)

duox_afat_heatmap <- ggplot(mec_exp,  aes(cellline, variable)) +
  geom_tile(aes(fill = value)) +
  labs(y = "DUOX1", x=element_blank()) +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y = element_text(color="black"),
        plot.margin=unit(c(1,1,-17,1), "mm")) +
  scale_fill_gradientn(colours=c("navyblue","darkmagenta","darkorange1"), 
                       na.value="transparent", 
                       name=expression(paste("TPM")),
                       trans = 'log2', 
                       breaks=c(1e-8,1e-6,1e-4,1e-2,1),
                       labels("1e-8","1e-6","1e-4","1e-2","1")) +
  coord_fixed(ratio = 1)
```






```{r worthless scatter}

expEgfr$median_egfr = apply(expEgfr[,c(2:4)], 1, medianWithoutNA)
exp89$median_duox = apply(exp89[,c(2:4)], 1, medianWithoutNA)

aucAfat_filt

comb_exp = merge(x=expEgfr[,c(1,5)], y=exp89[,c(1,5)], by="cellline")
comb_expauc = merge(x=comb_exp, y = aucErlo_filt[,c("cell_line", "median_auc")], by.x="cellline", by.y="cell_line", all.x=TRUE)
comb_expaucErlAfat = merge(x=comb_expauc, y = aucAfat_filt, by.x="cellline", by.y="cell_line", all.x=TRUE)

colnames(comb_expaucErlAfat) = c("cellline", "exp_egfr", "exp_duox", "auc_erl", "auc_afat")
mec=melt(comb_expaucErlAfat, id.vars=c("cellline", "exp_egfr", "exp_duox"))


mec$value[which(is.na(mec$value))]=0

ggplot(mec[which(mec$variable=="auc_erl"),]) +
  geom_point(aes(x=exp_egfr, y=exp_duox, size=value, colour=variable)) +
  xlim(0,15) +
  ylim(0,3)
```